const baseLessons=[
{id:1,title:'Subestação alimentando um CCM',short:'Dimensionamento da fonte, transformador, QGBT, cabos e tensão 380/220 V.',cat:['dimensionamento'],objectives:['Organizar as cargas industriais','Calcular demanda e corrente','Selecionar o transformador','Dimensionar o alimentador do QGBT'],quiz:{q:'Qual corrente aproximada corresponde a 225 kVA em 380 V trifásico?',o:['197 A','342 A','591 A'],a:1},slides:['01-capa.webp','02-cargas.webp','03-demanda.webp','04-tensao-380v.webp','05-transformador.webp','06-corrente-qgbt.webp','07-qgbt-cabos.webp','08-ndu-energisa.webp']},
{id:2,title:'Correção do fator de potência',short:'Motor de 25 cv em 220 V, cálculo de kvar e proteção do banco de capacitores.',cat:['dimensionamento','protecao'],objectives:['Diferenciar kW, kVA e kvar','Calcular potência elétrica do motor','Determinar a compensação reativa','Selecionar e proteger o banco'],quiz:{q:'A unidade usada para potência reativa é:',o:['kW','kVA','kvar'],a:2},slides:['01-capa.webp','02-dados-motor.webp','03-triangulo-potencias.webp','04-potencia-motor.webp','05-calculo-banco.webp','06-escolha-comercial.webp','07-protecao-banco.webp']},
{id:3,title:'Partidas de motores',short:'Comparação entre partida direta, estrela-triângulo e Soft-Starter para motor de 15 cv.',cat:['dimensionamento','protecao'],objectives:['Comparar correntes de partida','Reconhecer limitações da estrela-triângulo','Dimensionar uma Soft-Starter','Definir proteção e parametrização'],quiz:{q:'Qual solução permite rampa eletrônica de tensão e corrente?',o:['Partida direta','Soft-Starter','Chave seccionadora'],a:1},slides:['01-capa.webp','02-dados-motor.webp','03-comparacao.webp','04-direta-estrela.webp','05-dimensionamento.webp','06-circuito-potencia.webp','07-parametrizacao.webp','08-instalacao.webp','09-resultado.webp']},
{id:4,title:'Seletividade e curto-circuito',short:'Do elo fusível de MT ao quadro de motores: método simplificado e profissional.',cat:['protecao','dimensionamento'],objectives:['Estimar Icc no transformador','Somar impedâncias dos circuitos','Comparar método simplificado e complexo','Coordenar disjuntores e fusíveis'],quiz:{q:'O poder de interrupção Icu do disjuntor deve ser:',o:['Menor que a carga','Maior ou igual à Icc no ponto','Igual à corrente nominal do motor'],a:1},slides:['01-capa.webp','02-curto-trafo.webp','03-metodo-simplificado.webp','04-metodo-profissional.webp','05-cabos.webp','06-disjuntores.webp','07-resultado.webp']},
{id:5,title:'Aterramento industrial + SPDA',short:'Malha, hastes, BEP, equipotencialização, DPS e proteção de automação.',cat:['protecao','dimensionamento'],objectives:['Medir resistividade pelo método Wenner','Estimar a quantidade de hastes','Integrar SPDA, BEP e malha','Coordenar DPS e aterramento funcional'],quiz:{q:'O aterramento do CLP deve usar uma haste isolada da malha principal?',o:['Sim, sempre','Não; deve integrar a equipotencialização','Somente em 380 V'],a:1},slides:['01-capa.webp','02-risco.webp','03-equipotencial.webp','04-wenner.webp','05-hastes.webp','06-spda.webp','07-malha.webp','08-dps.webp','09-equipamentos.webp','10-checklist.webp']},
{id:6,title:'Cálculo luminotécnico',short:'Lúmens, cavidades zonais, ponto a ponto, uniformidade e softwares aplicáveis.',cat:['dimensionamento'],objectives:['Diferenciar lúmen, candela e lux','Aplicar o método dos lúmens','Calcular a razão de cavidade','Validar distribuição e uniformidade'],quiz:{q:'Um lux equivale a:',o:['1 lúmen por metro quadrado','1 candela por watt','1 kvar por metro'],a:0},slides:['01-capa.webp','02-grandezas.webp','03-ambiente.webp','04-lumens.webp','05-cavidades.webp','06-uniformidade.webp','07-ponto-a-ponto.webp','08-verificacoes.webp','09-softwares.webp','10-medicao.webp']},
{id:7,title:'Memorial descritivo',short:'Como transformar cálculos e desenhos em um documento executivo e rastreável.',cat:['documentacao'],objectives:['Definir escopo e premissas','Especificar materiais e proteções','Descrever execução e ensaios','Organizar entregáveis e as built'],quiz:{q:'Memorial descritivo e memória de cálculo são o mesmo documento?',o:['Sim','Não; possuem funções complementares','Somente em baixa tensão'],a:1},slides:['01-capa.webp','02-conceito.webp','03-escopo.webp','04-premissas.webp','05-distribuicao.webp','06-cabos.webp','07-automacao.webp','08-spda.webp','09-ensaios.webp','10-entrega.webp']}
];
let lessons=[...baseLessons];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={lesson:null,slide:0,filter:'all',query:'',deferred:null};
const completed=()=>JSON.parse(localStorage.getItem('microaulas-completed')||'[]');
const saveCompleted=v=>localStorage.setItem('microaulas-completed',JSON.stringify(v));
const path=(l,file)=>/^(https?:|blob:|data:)/.test(file||'')?file:`assets/microaulas/${String(l.id).padStart(2,'0')}/${file}`;
function renderLessons(){const done=completed();const q=state.query.toLowerCase();const visible=lessons.filter(l=>(state.filter==='all'||l.cat.includes(state.filter))&&(`${l.title} ${l.short} ${l.objectives.join(' ')}`.toLowerCase().includes(q)));$('#lessonGrid').innerHTML=visible.map(l=>`<article class="lesson-card" data-id="${l.id}" tabindex="0" role="button" aria-label="Abrir Microaula ${l.id}: ${l.title}"><div class="card-cover"><img src="${path(l,l.slides[0])}" alt="Capa da Microaula ${l.id}" loading="lazy"><span class="module-no">MICROAULA ${String(l.id).padStart(2,'0')}</span>${done.includes(l.id)?'<span class="done-badge">✓ CONCLUÍDA</span>':''}</div><div class="card-body"><h3>${l.title}</h3><p>${l.short}</p><div class="card-meta"><span>${l.slides.length} telas</span><span class="card-open">ABRIR →</span></div></div></article>`).join('');$('#emptyState').hidden=visible.length>0;$$('.lesson-card').forEach(c=>{c.onclick=()=>openLesson(+c.dataset.id);c.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openLesson(+c.dataset.id)}}});renderProgress()}
function renderProgress(){const done=completed().filter(id=>lessons.some(l=>l.id===id));const pct=lessons.length?Math.round(done.length/lessons.length*100):0;$('#progressRing').style.setProperty('--p',pct);$('#progressPercent').textContent=`${pct}%`;$('#progressDetail').textContent=`${done.length} de ${lessons.length} módulos concluídos`;const next=lessons.find(l=>!done.includes(l.id));$('#progressLabel').textContent=lessons.length&&done.length===lessons.length?'Trilha concluída!':next?`Próxima: Microaula ${next.id}`:'Nenhuma microaula publicada';$('#roadmapLine').style.gridTemplateColumns=`repeat(${Math.min(Math.max(lessons.length,1),7)},1fr)`;$('#roadmapLine').innerHTML=lessons.map(l=>`<div class="road-step ${done.includes(l.id)?'done':''}" data-step="${done.includes(l.id)?'✓':l.id}"><strong>${l.title}</strong><span>${l.slides.length} telas</span></div>`).join('');document.querySelector('.hero-actions a').textContent=`Ver ${lessons.length} microaulas`;const totalSlides=lessons.reduce((n,l)=>n+l.slides.length,0);const stats=$$('.hero-stats strong');if(stats[0])stats[0].textContent=lessons.length;if(stats[1])stats[1].textContent=totalSlides}
function openLesson(id,slide=0){state.lesson=lessons.find(l=>l.id===id);state.slide=Math.min(slide,state.lesson.slides.length-1);$('#viewerKicker').textContent=`MICROAULA ${String(id).padStart(2,'0')} • ${state.lesson.slides.length} TELAS`;$('#viewerTitle').textContent=state.lesson.title;$('#objectivesList').innerHTML=state.lesson.objectives.map(x=>`<li>${x}</li>`).join('');$('#notesArea').value=localStorage.getItem(`microaula-note-${id}`)||'';buildQuiz();buildThumbs();updateSlide();updateCompleteButton();$('#lessonDialog').showModal();localStorage.setItem('microaulas-last',JSON.stringify({id,slide:state.slide}))}
function updateSlide(){const l=state.lesson;const image=$('#slideImage');image.src=path(l,l.slides[state.slide]);image.alt=`Microaula ${l.id}, tela ${state.slide+1} de ${l.slides.length}`;image.style.cssText='display:block;width:auto!important;height:auto!important;max-width:100%!important;max-height:100%!important;min-width:0!important;min-height:0!important;object-fit:contain!important;object-position:center!important';$('#slideCounter').textContent=`${state.slide+1} / ${l.slides.length}`;$$('.thumb').forEach((t,i)=>t.classList.toggle('active',i===state.slide));$('.thumb.active')?.scrollIntoView({inline:'center',block:'nearest',behavior:'smooth'});localStorage.setItem('microaulas-last',JSON.stringify({id:l.id,slide:state.slide}))}
function changeSlide(delta){state.slide=(state.slide+delta+state.lesson.slides.length)%state.lesson.slides.length;updateSlide()}
function buildThumbs(){$('#thumbs').innerHTML=state.lesson.slides.map((s,i)=>`<button class="thumb ${i===state.slide?'active':''}" data-i="${i}" aria-label="Ir para tela ${i+1}"><img src="${path(state.lesson,s)}" alt="" loading="lazy"></button>`).join('');$$('.thumb').forEach(t=>t.onclick=()=>{state.slide=+t.dataset.i;updateSlide()})}
function buildQuiz(){const q=state.lesson.quiz;$('#quizQuestion').textContent=q.q;$('#quizOptions').innerHTML=q.o.map((x,i)=>`<button class="quiz-option" data-i="${i}">${x}</button>`).join('');$('#quizFeedback').textContent='';$$('.quiz-option').forEach(b=>b.onclick=()=>{const ok=+b.dataset.i===q.a;$$('.quiz-option').forEach((x,i)=>{x.disabled=true;if(i===q.a)x.classList.add('correct')});if(!ok)b.classList.add('wrong');$('#quizFeedback').textContent=ok?'Correto! Você consolidou este conceito.':'Revise a microaula e compare novamente.'})}
function updateCompleteButton(){const done=completed().includes(state.lesson.id);$('#completeBtn').classList.toggle('is-done',done);$('#completeBtn').textContent=done?'✓ Microaula concluída':'✓ Marcar como concluída'}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').classList.remove('show'),2200)}
$('#searchInput').oninput=e=>{state.query=e.target.value;renderLessons()};$('#filters').onclick=e=>{const b=e.target.closest('.chip');if(!b)return;state.filter=b.dataset.filter;$$('.chip').forEach(x=>x.classList.toggle('active',x===b));renderLessons()};
$('#prevBtn').onclick=()=>changeSlide(-1);$('#nextBtn').onclick=()=>changeSlide(1);$('#closeBtn').onclick=()=>$('#lessonDialog').close();$('#lessonDialog').onclick=e=>{if(e.target===$('#lessonDialog'))$('#lessonDialog').close()};
function updateLightbox(){const l=state.lesson;if(!l)return;$('#lightboxImage').src=path(l,l.slides[state.slide]);$('#lightboxImage').alt=`Microaula ${l.id}, tela ${state.slide+1} de ${l.slides.length}, ampliada`;$('#lightboxCounter').textContent=`Microaula ${String(l.id).padStart(2,'0')} • ${state.slide+1} / ${l.slides.length}`;$('#lightboxCanvas').classList.remove('zoomed');updateSlide()}
function openLightbox(){$('#imageLightbox').hidden=false;document.body.style.overflow='hidden';updateLightbox();$('#lightboxClose').focus()}
function closeLightbox(){$('#imageLightbox').hidden=true;document.body.style.overflow='';$('#lightboxCanvas').classList.remove('zoomed');$('#expandImageBtn').focus()}
function lightboxSlide(delta){state.slide=(state.slide+delta+state.lesson.slides.length)%state.lesson.slides.length;updateLightbox()}
$('#expandImageBtn').onclick=openLightbox;$('#lightboxClose').onclick=closeLightbox;$('#lightboxPrev').onclick=()=>lightboxSlide(-1);$('#lightboxNext').onclick=()=>lightboxSlide(1);$('#lightboxImage').onclick=()=>$('#lightboxCanvas').classList.toggle('zoomed');$('#imageLightbox').onclick=e=>{if(e.target===$('#imageLightbox'))closeLightbox()};
$('#completeBtn').onclick=()=>{const d=completed();const i=d.indexOf(state.lesson.id);i<0?d.push(state.lesson.id):d.splice(i,1);saveCompleted(d);updateCompleteButton();renderLessons();toast(i<0?'Microaula concluída!':'Conclusão removida')};
$('#notesArea').oninput=e=>{localStorage.setItem(`microaula-note-${state.lesson.id}`,e.target.value);$('#saveStatus').textContent='Salvando...';clearTimeout(state.noteTimer);state.noteTimer=setTimeout(()=>$('#saveStatus').textContent='Salvo automaticamente',500)};
$$('.panel-tab').forEach(b=>b.onclick=()=>{$$('.panel-tab').forEach(x=>x.classList.toggle('active',x===b));$$('.panel-content').forEach(x=>x.classList.remove('active'));$(`#panel-${b.dataset.panel}`).classList.add('active')});
function togglePresentation(){const d=$('#lessonDialog');d.classList.toggle('presentation');if(d.classList.contains('presentation'))d.requestFullscreen?.();else if(document.fullscreenElement)document.exitFullscreen?.()}$('#presentationBtn').onclick=togglePresentation;
document.addEventListener('keydown',e=>{if(!$('#imageLightbox').hidden){if(e.key==='ArrowRight')lightboxSlide(1);if(e.key==='ArrowLeft')lightboxSlide(-1);if(e.key==='Escape')closeLightbox();return}if(!$('#lessonDialog').open)return;if(e.key==='ArrowRight')changeSlide(1);if(e.key==='ArrowLeft')changeSlide(-1);if(e.key.toLowerCase()==='f')togglePresentation();if(e.key==='Escape'&&$('#lessonDialog').classList.contains('presentation'))$('#lessonDialog').classList.remove('presentation')});
let sx=0;$('#slideStage').addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});$('#slideStage').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>60)changeSlide(dx<0?1:-1)},{passive:true});
let lightboxSx=0;$('#lightboxCanvas').addEventListener('touchstart',e=>lightboxSx=e.touches[0].clientX,{passive:true});$('#lightboxCanvas').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-lightboxSx;if(Math.abs(dx)>60&&!$('#lightboxCanvas').classList.contains('zoomed'))lightboxSlide(dx<0?1:-1)},{passive:true});
$('#continueBtn').onclick=()=>{const last=JSON.parse(localStorage.getItem('microaulas-last')||'null');if(last)openLesson(last.id,last.slide);else openLesson(1)};$('#resetBtn').onclick=()=>{if(confirm('Deseja realmente zerar o progresso das microaulas?')){saveCompleted([]);renderLessons();toast('Progresso reiniciado')}};
function setTheme(theme){document.documentElement.classList.toggle('light',theme==='light');localStorage.setItem('microaulas-theme',theme);$('#themeBtn').textContent=theme==='light'?'☾':'☼'}setTheme(localStorage.getItem('microaulas-theme')||'dark');$('#themeBtn').onclick=()=>setTheme(document.documentElement.classList.contains('light')?'dark':'light');
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferred=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(!state.deferred)return;state.deferred.prompt();await state.deferred.userChoice;state.deferred=null;$('#installBtn').hidden=true};
window.microaulasAPI={
  getLessons:()=>lessons.map(l=>({...l})),
  getBaseLessons:()=>baseLessons.map(l=>({...l})),
  setCloudLessons(cloud=[]){const byId=new Map(baseLessons.map(l=>[String(l.id),{...l,source:'local'}]));cloud.forEach(c=>{const key=String(c.id);if(c.deleted||c.published===false)byId.delete(key);else byId.set(key,{...c,id:Number(c.id),source:'firebase'})});lessons=[...byId.values()].filter(l=>Array.isArray(l.slides)&&l.slides.length).sort((a,b)=>(a.order||a.id)-(b.order||b.id));renderLessons()},
  refresh:renderLessons,
  toast
};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));renderLessons();
